# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

inherit distutils

MY_PN="SquareMap"
MY_PV="${PV/_beta/b}"
MY_P="${MY_PN}-${MY_PV}"

DESCRIPTION="Hierarchic data-visualisation control for wxPython"
HOMEPAGE="https://launchpad.net/squaremap"
SRC_URI="http://pypi.python.org/packages/source/S/SquareMap/${MY_P}.zip"
LICENSE="BSD-2"
KEYWORDS="amd64"
SLOT="0"
IUSE=""
S="${WORKDIR}/${MY_P}"
DEPEND="app-arch/unzip
	dev-python/setuptools"

