# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

PYTHON_MODNAME="pygraph"

inherit distutils


DESCRIPTION="A library for working with graphs in Python"
HOMEPAGE="http://code.google.com/p/python-graph/"
SRC_URI="http://python-graph.googlecode.com/files/${P}.zip"
LICENSE="MIT"
KEYWORDS="~amd64"
SLOT="0"
IUSE=""
S="${WORKDIR}/${PN}"
DEPEND="app-arch/unzip
	dev-python/setuptools"
RDEPEND="dev-python/pydot"

src_test() {
	PYTHONPATH=. "${python}" setup.py test || die "tests failed"
}

